apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 'https://github.com/Marosko123/ambulance-webapi//deployments/kustomize/install'
- http-route.yaml

labels:
  - pairs:
      app.kubernetes.io/component: mb-ambulance-webapi
      wac-fiit.github.io/component: backend
