apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: mb-ambulance-wl
spec:
  title: "Ambulance Waiting List - Maros Bednar"
  description: "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Maros Bednar"
  azureLink: "https://mb-ambulance-wl-b8cfd3fggrhte4ah.germanywestcentral-01.azurewebsites.net/"
  frontendRepoUrl: "https://github.com/Marosko123/ambulance-ufe"
  backendRepoUrl: "https://github.com/Marosko123/ambulance-webapi"
  gitopsRepoUrl: "https://github.com/Marosko123/ambulance-gitops"
