apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: bednarmaros341/ambulance-ufe
  newName: bednarmaros341/ambulance-ufe # {"$imagepolicy": "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260224.1339 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: bednarmaros341/ambulance-wl-webapi
  newName: bednarmaros341/ambulance-wl-webapi # {"$imagepolicy": "wac-hospital:ambulance-webapi:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
